// Minimal sdkconfig.h for syntax checking
// Generated from sdkconfig.defaults.esp32s3
#pragma once

#define CONFIG_IDF_TARGET_ESP32S3 1
#define CONFIG_ESPTOOLPY_FLASHSIZE_16MB 1
#define CONFIG_ESPTOOLPY_FLASHMODE_QIO 1
#define CONFIG_ESP_DEFAULT_CPU_FREQ_MHZ_240 1
#define CONFIG_SPIRAM 1
#define CONFIG_SPIRAM_MODE_OCT 1
#define CONFIG_SPIRAM_SPEED_80M 1
#define CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL 512
#define CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL 65536
#define CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC 1
#define CONFIG_ESP_WIFI_STATIC_RX_BUFFER_NUM 3
#define CONFIG_ESP_WIFI_DYNAMIC_RX_BUFFER_NUM 6
#define CONFIG_ESP_WIFI_RX_BA_WIN 3
#define CONFIG_LWIP_TCPIP_RECVMBOX_SIZE 16
#define CONFIG_MBEDTLS_DYNAMIC_FREE_CONFIG_DATA 1
#define CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB 1
#define CONFIG_ESP32S3_DATA_CACHE_LINE_64B 1
#define CONFIG_SR_WN_WN9_NIHAOXIAOZHI_TTS 1
#define CONFIG_ESP_SYSTEM_EVENT_TASK_STACK_SIZE 4096
#define CONFIG_LV_USE_SNAPSHOT 1

// Additional common ESP-IDF configs
#define CONFIG_FREERTOS_HZ 100
#define CONFIG_FREERTOS_UNICORE 0
#define CONFIG_FREERTOS_NUMBER_OF_CORES 2
#define CONFIG_FREERTOS_MAX_TASK_NAME_LEN 16
#define CONFIG_FREERTOS_TASK_NOTIFICATION_ARRAY_ENTRIES 1
#define CONFIG_FREERTOS_SMP 0
#define CONFIG_FREERTOS_IDLE_TASK_STACK_SIZE 1536
#define CONFIG_ESP_MAIN_TASK_STACK_SIZE 8192
#define CONFIG_ESP_MAIN_TASK_AFFINITY_CPU0 1
#define CONFIG_IDF_TARGET_ESP32S3 1
#define CONFIG_ESP32S3_DEFAULT_CPU_FREQ_MHZ 240
#define CONFIG_XTAL_FREQ 40
#define CONFIG_ESP_CONSOLE_UART_NUM 0
#define CONFIG_ESP_CONSOLE_UART_BAUDRATE 115200

// Log configuration
#define CONFIG_LOG_DEFAULT_LEVEL 3
#define CONFIG_LOG_MAXIMUM_LEVEL 4
#define CONFIG_LOG_TIMESTAMP_SOURCE_RTOS 1
#define CONFIG_LOG_COLORS 1

// Board identification (from CMake target_compile_definitions)
#define BOARD_TYPE "bread-compact-wifi"
#define BOARD_NAME "bread-compact-wifi"

// Additional bootloader/flash configs
#define CONFIG_BOOTLOADER_LOG_LEVEL 3
#define CONFIG_BOOTLOADER_SPI_WP_PIN 46
#define CONFIG_ESP_PHY_ENABLE_USB 0
#define CONFIG_ESP_PHY_MAX_WIFI_TX_POWER 20
#define CONFIG_ESP_WIFI_ENABLED 1
#define CONFIG_ESP_WIFI_SOFTAP_SUPPORT 1
#define CONFIG_LWIP_MAX_SOCKETS 10
